[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["corepack enable", "pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm --recursive --stream build"]

[start]
cmd = "cd packages/dwn-server && ./entrypoint.sh"