/**
 * Canonical type definitions for the Enbox Connect v2 handshake.
 *
 * Connect is a capability delegation protocol for DWN access: an app requests
 * scoped permission grants from a wallet (provider) and receives a delegate
 * DID with the granted permissions. One protocol (envelope + payload +
 * approval ceremony + completion) is carried over per-channel transports
 * (relay/QR/deep-link, popup postMessage). Both directions are signed AND
 * encrypted on every channel.
 *
 * @module
 */

import type { Jwk } from '@enbox/crypto';
import type { PortableDid } from '@enbox/dids';
import type { DataEncodedRecordsWriteMessage, PermissionScope, ProtocolDefinition } from '@enbox/dwn-sdk-js';

// Grant-level connect session metadata is defined in `@enbox/dwn-sdk-js`
// (the `PermissionGrant` message type depends on it), so the kernel re-exports
// it rather than duplicating the definition.
export type { ConnectSessionMetadata, ConnectSessionTransport } from '@enbox/dwn-sdk-js';

/**
 * Opaque token a wallet delivers in place of a sealed response when the user
 * denies a connect request. Transports return it verbatim from
 * {@link ConnectTransport.awaitResponse}; the client maps it to an undefined
 * {@link ConnectResult}.
 */
export const CONNECT_DENIED_TOKEN = 'DENIED';

/**
 * The protocols of permissions requested, along with the definition and permission scopes for each protocol.
 */
export type ConnectPermissionRequest = {
  /**
   * The definition of the protocol the permissions are being requested for.
   * In the event that the protocol is not already installed, the wallet will install this given protocol definition.
   */
  protocolDefinition: ProtocolDefinition;

  /** The scope of the permissions being requested for the given protocol */
  permissionScopes: PermissionScope[];
};

/**
 * Client/environment details captured by the connect client for wallet session display.
 *
 * This data is self-reported by the requester, unauthenticated, and intended
 * only as display hints. Wallets must not treat it as verified app identity.
 */
export type ConnectClientMetadata = {
  /** Origin of the requesting app, when known. */
  origin?: string;

  /** Browser user agent string, when available. */
  userAgent?: string;

  /** Platform/device hint, when available. */
  platform?: string;

  /** Primary language, when available. */
  language?: string;

  /** Language preference list, when available. */
  languages?: string[];

  /** IANA timezone, when available. */
  timezone?: string;
};

/** Identifies the user-facing purpose of a connect request. */
export type ConnectRequestType = 'connect' | 'refresh';

/**
 * Describes how the wallet must deliver its sealed response back to the app.
 *
 * - `direct_post`: the wallet POSTs the response to `callbackUrl` (relay flows).
 * - `post_message`: the wallet posts the response over the popup postMessage
 *   channel that carried the request (browser popup flows).
 */
export type ReplyDescriptor =
  | { mode: 'direct_post'; callbackUrl: string }
  | { mode: 'post_message' };

/**
 * A connect request from an app to a wallet, asking for DWN permissions.
 *
 * The app creates this, signs it as a JWT with `clientDid`, seals it as a JWE
 * (see the envelope module), and delivers it over a channel transport. The
 * wallet opens, verifies, and displays it in a consent UI.
 */
export type ConnectRequest = {
  /** Ephemeral DID (did:jwk) used for request signing and response addressing. */
  clientDid: string;

  /** Human-readable name of the requesting application, shown in the consent UI. */
  appName: string;

  /** Optional icon URL for the requesting application, shown in the consent UI. */
  appIcon?: string;

  /** Optional client/environment metadata for wallet session display. */
  clientMetadata?: ConnectClientMetadata;

  /** DWN protocols and permission scopes being requested. */
  permissionRequests: ConnectPermissionRequest[];

  /** Preferred session TTL in seconds. Wallets may clamp this to their policy maximum. */
  requestedSessionTtlSeconds?: number;

  /**
   * Optional delegate DID supplied by the requester.
   *
   * When present, the wallet grants permissions to this DID instead of
   * minting a new delegate DID and returning its private key material.
   */
  delegateDid?: string;

  /**
   * User-facing request purpose. Absent means a normal connect;
   * `refresh` asks the wallet to re-grant access to the existing `delegateDid`.
   */
  requestType?: ConnectRequestType;

  /** Supported DID methods for the connected identity. */
  supportedDidMethods: string[];

  /** Anti-replay nonce (random base64url), echoed back in the response. */
  nonce: string;

  /** State correlator for matching request to response (random base64url). */
  state: string;

  /**
   * Fresh X25519 public key (JWK) generated by the client for this handshake.
   * The wallet seals its response to this key with ECDH-ES.
   */
  responseKey: Jwk;

  /** How the wallet must deliver its sealed response. */
  reply: ReplyDescriptor;
};

/** Per-grant revocation mapping for session-bound self-revocation on disconnect. */
export type SessionRevocation = {
  /** Record ID of the session permission grant. */
  grantId: string;

  /** Record ID of the contextId-scoped revocation grant covering `grantId`. */
  revocationGrantId: string;
};

/**
 * A connect response from a wallet, granting DWN permissions.
 *
 * The wallet creates this after user consent, signs it as a JWT, seals it as
 * a JWE to the request's `responseKey`, and delivers it over the channel
 * transport. The app opens it with value checks (aud, nonce echo, state echo,
 * expiry window) before trusting any field.
 */
export type ConnectResponse = {
  /** The wallet owner's real DID that authorised the delegation. */
  providerDid: string;

  /** The delegate DID identifier that received the grants. */
  delegateDid: string;

  /** Audience — must match the `clientDid` from the request. */
  aud: string;

  /** Issued-at timestamp (Unix seconds). */
  iat: number;

  /** Expiration timestamp (Unix seconds); `iat + 600`. */
  exp: number;

  /** Echo of the request nonce. */
  nonce: string;

  /** Echo of the request state. */
  state: string;

  /** DWN permission grant messages (serialised RecordsWrite with encoded data). */
  delegateGrants: DataEncodedRecordsWriteMessage[];

  /**
   * The delegate DID's full portable form, including private keys.
   *
   * Present for wallet-minted delegate sessions and omitted when the request
   * supplied its own delegate DID.
   */
  delegatePortableDid?: PortableDid;

  /** Per-grant revocation mappings for session-bound self-revocation on disconnect. */
  sessionRevocations: SessionRevocation[];
};

/**
 * Result of a successful connect handshake.
 *
 * Contains the delegated credentials returned by the wallet. All connect
 * handlers (browser popup, relay, CLI, etc.) return this shape on success;
 * it is the input to the auth completion seam.
 */
export type ConnectResult = {
  /** The portable delegate DID (includes private keys). */
  delegatePortableDid: PortableDid;

  /** Permission grants for the requested protocols. */
  delegateGrants: DataEncodedRecordsWriteMessage[];

  /** The DID of the identity the user approved (the wallet owner's DID). */
  connectedDid: string;

  /** Per-grant revocation mappings for session-bound self-revocation on disconnect. */
  sessionRevocations: SessionRevocation[];
};

/**
 * Output of the wallet-side approval ceremony (grants minted, protocols
 * configured, revocation grants created) that the kernel seals into a
 * {@link ConnectResponse}.
 */
export type ConnectApproval = {
  /** The delegate DID identifier that received the grants. */
  delegateDid: string;

  /**
   * The delegate DID's full portable form, including private keys. Required
   * for wallet-minted delegate sessions; must be omitted when the request
   * pre-supplied its own delegate DID.
   */
  delegatePortableDid?: PortableDid;

  /** DWN permission grant messages created for the delegate. */
  delegateGrants: DataEncodedRecordsWriteMessage[];

  /** Per-grant revocation mappings for session-bound self-revocation on disconnect. */
  sessionRevocations: SessionRevocation[];
};

/**
 * Channel-specific encryption input for sealing a connect request.
 *
 * - `dir`: relay/QR/deep-link flows — a fresh single-use 32-byte symmetric key
 *   that travels only in the wallet URI fragment.
 * - `ecdh-es`: popup flows — the wallet's ephemeral X25519 public key from its
 *   `loaded` beacon, with the wallet origin bound into the JWE `apv` header.
 */
export type ConnectRequestEncryption =
  | { mode: 'dir'; requestKey: Uint8Array }
  | { mode: 'ecdh-es'; walletEpk: Jwk; walletOrigin: string };

/**
 * Channel-specific decryption input for opening a sealed connect request on
 * the wallet side. The `ecdh-es` variant carries the wallet's own origin so
 * the JWE `apv` binding can be value-checked.
 */
export type ConnectRequestDecryption =
  | { mode: 'dir'; requestKey: Uint8Array }
  | { mode: 'ecdh-es'; recipientPrivateKey: Jwk; walletOrigin: string };

/**
 * Wallet URI handoff produced by transports that hand the request pointer to
 * the user out-of-band (QR code or deep link) instead of delivering it
 * in-channel.
 */
export type WalletUriHandoff = {
  /** Wallet URI carrying the `request_uri` and `encryption_key` fragment parameters. */
  walletUri: string;

  /** The relay `request_uri` where the wallet fetches the sealed request. */
  requestUri: string;

  /** Seconds until the pushed request expires on the relay. */
  expiresIn: number;
};

/**
 * Channel profile a transport supplies to the client before the request is
 * sealed: the encryption input, the reply descriptor, and the transport's
 * response correlator.
 */
export type ConnectRequestProfile = {
  /** Encryption input the client must use with `sealRequest`. */
  encryption: ConnectRequestEncryption;

  /** Reply descriptor the client must embed in the request. */
  reply: ReplyDescriptor;

  /**
   * State correlator (random base64url) echoed from the value the client
   * passed to {@link ConnectTransport.requestProfile}. The client embeds it in
   * the request; the transport uses it to await the response.
   */
  state: string;
};

/**
 * A channel transport that carries sealed connect envelopes between an app
 * and a wallet (relay HTTP, popup postMessage, loopback in tests).
 *
 * Transports never see plaintext: `deliverRequest` and `awaitResponse` handle
 * ciphertext only. `requestProfile()` supplies the channel-specific sealing
 * profile so the client stays channel-agnostic.
 */
export interface ConnectTransport {
  /** Whether responses on this channel are PIN-strengthened (relay flows). */
  readonly requiresPin: boolean;

  /**
   * Returns the channel profile for the next handshake: encryption input,
   * reply descriptor, and the echoed state correlator. Must be called before
   * {@link deliverRequest}.
   *
   * @param state - The client-generated state correlator the transport must
   *                use to await the response.
   */
  requestProfile(state: string): Promise<ConnectRequestProfile>;

  /**
   * Delivers the sealed request JWE to the wallet's channel. Returns a
   * {@link WalletUriHandoff} when the user must carry the request pointer to
   * the wallet out-of-band (QR/deep link), or `void` for in-channel delivery.
   */
  deliverRequest(jwe: string): Promise<void | WalletUriHandoff>;

  /**
   * Awaits the wallet's response ciphertext. Resolves with the sealed
   * response JWE, or the literal {@link CONNECT_DENIED_TOKEN} when the user
   * denied the request. Rejects on channel timeout.
   */
  awaitResponse(): Promise<string>;

  /**
   * Best-effort completion signal back to the wallet side: the client
   * fetched the response and opened it successfully, so the wallet UI can
   * flip its pairing screen to a confirmed "connected" state instead of
   * asking the user to dismiss it blind. Observational only — it carries no
   * payload, proves nothing beyond liveness, and callers must swallow
   * failures (channels and relays without completion support simply never
   * deliver it).
   */
  confirmComplete?(): Promise<void>;
}
