// export everything that we want to be consumable
export type { DwnConfig } from './dwn.js';
export type { EventListener, EventLog, EventLogEntry, EventLogReadOptions, EventLogReadResult, EventLogSubscribeOptions, EventSubscription, MessageEvent, ProgressGapInfo, ProgressGapReason, ProgressToken, SubscriptionEose, SubscriptionEvent, SubscriptionListener, SubscriptionMessage, SubscriptionReply } from './types/subscriptions.js';
export type { AuthorizationModel, Descriptor, DelegatedGrantRecordsWriteMessage, GenericMessage, GenericMessageReply, GenericSignaturePayload, MessageSort, MessageSubscription, Pagination, QueryResultEntry, Status } from './types/message-types.js';
export type { MessagesFilter, MessagesReadMessage as MessagesReadMessage, MessagesReadReply as MessagesReadReply, MessagesReadReplyEntry as MessagesReadReplyEntry, MessagesReadDescriptor, MessagesSubscribeDescriptor, MessagesSubscribeMessage, MessagesSubscribeReply, MessagesSubscribeMessageOptions, MessagesSyncAction, MessagesSyncDescriptor, MessagesSyncDiffEntry, MessagesSyncMessage, MessagesSyncReply } from './types/messages-types.js';
export type { GT, LT, Filter, FilterValue, KeyValues, EqualFilter, OneOfFilter, RangeFilter, RangeCriterion, PaginationCursor, QueryOptions, RangeValue, StartsWithFilter } from './types/query-types.js';
export type { ProtocolsConfigureDescriptor, ProtocolDefinition, ProtocolTypes, ProtocolRuleSet, ProtocolsQueryFilter, ProtocolsConfigureMessage, ProtocolsQueryMessage, ProtocolsQueryReply, ProtocolActionRule, ProtocolDeliveryStrategy, ProtocolPathEncryption, ProtocolsQueryDescriptor, ProtocolRecordLimitDefinition, ProtocolSizeDefinition, ProtocolTagsDefinition, ProtocolTagSchema, ProtocolType, ProtocolUses } from './types/protocols-types.js';
export { ProtocolRecordLimitStrategy } from './types/protocols-types.js';
export type { DataEncodedRecordsWriteMessage, RecordsCountDescriptor, RecordsCountMessage, RecordsCountReply, RecordsDeleteMessage, RecordsFilter, RecordsQueryMessage, RecordsQueryReply, RecordsQueryReplyEntry, RecordsReadMessage, RecordsReadReply, RecordsSubscribeDescriptor, RecordsSubscribeMessage, RecordsSubscribeReply, RecordsWriteDescriptor, RecordsWriteTags, RecordsWriteTagValue, RecordsWriteMessage, RecordsWriteSignaturePayload, RecordsDeleteDescriptor, RecordsQueryDescriptor, RecordsReadDescriptor, RecordsSubscribeMessageOptions, RecordsWriteMessageOptions, InternalRecordsWriteMessage, RecordEvent, RecordsWriteTagsFilter } from './types/records-types.js';
export type { GeneralJws, SignatureEntry } from './types/jws-types.js';
export { authenticate } from './core/auth.js';
export { CoreProtocolRegistry } from './core/core-protocol.js';
export { PERMISSIONS_REVOCATION_PATH } from './core/constants.js';
export type { CoreProtocol, CoreProtocolStores } from './core/core-protocol.js';
export { AllowAllTenantGate } from './core/tenant-gate.js';
export type { ActiveTenantCheckResult, TenantGate } from './core/tenant-gate.js';
export { Cid } from './utils/cid.js';
export { RecordsCount } from './interfaces/records-count.js';
export type { RecordsCountOptions } from './interfaces/records-count.js';
export { RecordsQuery } from './interfaces/records-query.js';
export type { RecordsQueryOptions } from './interfaces/records-query.js';
export type { DataStore, DataStorePutResult, DataStoreGetResult } from './types/data-store.js';
export type { ResumableTaskStore, ManagedResumableTask } from './types/resumable-task-store.js';
export { DataStream } from './utils/data-stream.js';
export { HdKey, KeyDerivationScheme } from './utils/hd-key.js';
export type { DerivedPrivateJwk } from './utils/hd-key.js';
export { Dwn } from './dwn.js';
export type { MessageOptions } from './dwn.js';
export { DwnConstant } from './core/dwn-constant.js';
export { DwnError, DwnErrorCode } from './core/dwn-error.js';
export { DwnInterfaceName, DwnMethodName } from './enums/dwn-interface-method.js';
export { Encoder } from './utils/encoder.js';
export { MessagesSubscribe as MessagesSubscribe } from './interfaces/messages-subscribe.js';
export type { MessagesSubscribeOptions as MessagesSubscribeOptions } from './interfaces/messages-subscribe.js';
export { Encryption, ContentEncryptionAlgorithm, KeyAgreementAlgorithm } from './utils/encryption.js';
export type { JweEncryption, JweRecipient, JweRecipientHeader, JweProtectedHeader, JweKeyUnwrapPayload } from './utils/encryption.js';
export { RecordsWrite } from './interfaces/records-write.js';
export type { EncryptionInput, KeyEncryptionInput, RecordsWriteOptions, CreateFromOptions } from './interfaces/records-write.js';
export { executeUnlessAborted } from './utils/abort.js';
export { Jws } from './utils/jws.js';
export type { KeyMaterial, PrivateKeyJwk, PublicKeyJwk, Jwk } from './types/jose-types.js';
export { Message } from './core/message.js';
export { MessagesRead as MessagesRead } from './interfaces/messages-read.js';
export type { MessagesReadOptions as MessagesReadOptions } from './interfaces/messages-read.js';
export { MessagesSync } from './interfaces/messages-sync.js';
export type { MessagesSyncOptions } from './interfaces/messages-sync.js';
export type { UnionMessageReply } from './core/message-reply.js';
export type { MessageStore, MessageStoreOptions } from './types/message-store.js';
export type { MessageInterface } from './types/message-interface.js';
export { PermissionGrant } from './protocols/permission-grant.js';
export { PermissionRequest } from './protocols/permission-request.js';
export { PermissionsProtocol } from './protocols/permissions.js';
export type { PermissionGrantCreateOptions, PermissionRequestCreateOptions, PermissionRevocationCreateOptions } from './protocols/permissions.js';
export { PrivateKeySigner } from './utils/private-key-signer.js';
export type { PrivateKeySignerOptions } from './utils/private-key-signer.js';
export { Protocols, parseCrossProtocolRef, isCrossProtocolRef, getRuleSetAtPath } from './utils/protocols.js';
export type { CrossProtocolRef } from './utils/protocols.js';
export { ProtocolsConfigure } from './interfaces/protocols-configure.js';
export type { ProtocolsConfigureOptions } from './interfaces/protocols-configure.js';
export { ProtocolsQuery } from './interfaces/protocols-query.js';
export type { ProtocolsQueryOptions } from './interfaces/protocols-query.js';
export { Records } from './utils/records.js';
export { RecordsDelete } from './interfaces/records-delete.js';
export type { RecordsDeleteOptions } from './interfaces/records-delete.js';
export { RecordsRead } from './interfaces/records-read.js';
export type { RecordsReadOptions } from './interfaces/records-read.js';
export { RecordsSubscribe } from './interfaces/records-subscribe.js';
export type { RecordsSubscribeOptions } from './interfaces/records-subscribe.js';
export { Secp256k1 } from './utils/secp256k1.js';
export { Secp256r1 } from './utils/secp256r1.js';
export type { SupportedCurve } from './jose/algorithms/signing/signature-algorithms.js';
export type { MessageSigner } from './types/signer.js';
export { SortDirection } from './types/query-types.js';
export type { EncryptionKeyDeriver, KeyDecrypter } from './types/encryption-types.js';
export { Time } from './utils/time.js';
export * from './types/permission-types.js';
export * from './types/records-types.js';

// concrete implementations of stores and event log
export { BlockstoreLevel } from './store/blockstore-level.js';
export type { BlockstoreLevelConfig } from './store/blockstore-level.js';
export { DataStoreLevel } from './store/data-store-level.js';
export type { DataStoreLevelConfig } from './store/data-store-level.js';
export { IndexLevel } from './store/index-level.js';
export type { CompoundIndexDefinition, IndexLevelConfig, IndexedItem, IndexLevelOptions } from './store/index-level.js';
export { createLevelDatabase, LevelWrapper } from './store/level-wrapper.js';
export type { CreateLevelDatabaseOptions, LevelDatabase, LevelWrapperConfig, LevelWrapperBatchOperation, LevelWrapperOptions, LevelWrapperIteratorOptions } from './store/level-wrapper.js';
export { MessageStoreLevel } from './store/message-store-level.js';
export type { MessageStoreLevelConfig } from './store/message-store-level.js';
export { ResumableTaskStoreLevel } from './store/resumable-task-store-level.js';
export type { ResumableTaskStoreLevelConfig } from './store/resumable-task-store-level.js';
export { EventEmitterEventLog } from './event-stream/event-emitter-event-log.js';
export type { EventEmitterEventLogConfig } from './event-stream/event-emitter-event-log.js';

// Sparse Merkle Tree and StateIndex
export type { StateIndex } from './types/state-index.js';
export { StateIndexLevel } from './state-index/state-index-level.js';
export type { StateIndexLevelConfig } from './state-index/state-index-level.js';
export { SparseMerkleTree } from './smt/sparse-merkle-tree.js';
export { SMTStoreLevel } from './smt/smt-store-level.js';
export { SMTStoreMemory } from './smt/smt-store-memory.js';
export type { Hash, SMTNode, SMTInternalNode, SMTLeafNode, SMTProof, SMTDiffResult, SMTNodeStore } from './types/smt-types.js';
export { hashChildren, hashEquals, hashKey, hashLeaf, hashToHex, hexToHash, getBit, initDefaultHashes, getDefaultHashes, SMT_DEPTH, ZERO_HASH } from './smt/smt-utils.js';

// test library exports
export type { GenerateFromRecordsWriteInput, GenerateFromRecordsWriteOut, GenerateGrantCreateInput, GenerateGrantCreateOutput, GenerateMessagesReadInput, GenerateMessagesReadOutput, GenerateMessagesSubscribeInput, GenerateMessagesSubscribeOutput, GenerateProtocolsConfigureInput, GenerateProtocolsConfigureOutput, GenerateProtocolsQueryInput, GenerateProtocolsQueryOutput, GenerateRecordsCountInput, GenerateRecordsCountOutput, GenerateRecordsDeleteInput, GenerateRecordsDeleteOutput, GenerateRecordsQueryInput, GenerateRecordsQueryOutput, GenerateRecordsSubscribeInput, GenerateRecordsSubscribeOutput, GenerateRecordsWriteInput, GenerateRecordsWriteOutput, Persona } from '../tests/utils/test-data-generator.js';
export { TestDataGenerator } from '../tests/utils/test-data-generator.js';
export { Poller } from '../tests/utils/poller.js';