import type { AsymmetricKeyConverter } from './key-converter.js';
import type { AsymmetricKeyGenerator } from './key-generator.js';
import type { Cipher } from './cipher.js';
import type { Hasher } from './hasher.js';
import type { KeyBytesDeriver } from './key-deriver.js';
import type { KeyIdentifier } from './identifier.js';
import type { KeyWrapper } from './key-wrapper.js';
import type { Signer } from './signer.js';
import type {
  BytesToPrivateKeyParams,
  BytesToPublicKeyParams,
  CipherParams,
  DeriveKeyBytesParams,
  DeriveKeyParams,
  DigestParams,
  GenerateKeyParams,
  GetPublicKeyParams,
  PrivateKeyToBytesParams,
  PublicKeyToBytesParams,
  SignParams,
  UnwrapKeyParams,
  VerifyParams,
  WrapKeyParams,
} from './params-direct.js';
import type {
  KmsDigestParams,
  KmsGenerateKeyParams,
  KmsGetKeyUriParams,
  KmsGetPublicKeyParams,
  KmsSignParams,
  KmsVerifyParams,
} from './params-kms.js';

import type { Jwk } from '../jose/jwk.js';

/**
 * The `DsaApi` interface integrates key generation, hashing, and signing functionalities,
 * designed for use with a Key Management System (KMS). It extends `AsymmetricKeyGenerator` for
 * generating asymmetric keys, `Hasher` for hash digest computations, and `Signer` for signing and
 * verifying operations.
 *
 * Concrete implementations of this interface are intended to be used with a KMS, which is
 * responsible for generating and storing cryptographic keys. The KMS is also responsible for
 * performing cryptographic operations using the keys it manages. The KMS is typically a cloud
 * service, but it can also be a hardware device or software application.
 *
 * Guidelines for implementing this interface:
 * - Must use JSON Web Keys ({@link Jwk | JWK}) as the key format.
 * - Must IANA registered JSON Object Signing and Encryption
 *   {@ link https://www.iana.org/assignments/jose/jose.xhtml#web-signature-encryption-algorithms | (JOSE)}
 *   names for algorithm, curves, etc. whenever possible.
 * - All I/O that interacts with private or secret keys must be done via reference using a
 *   {@link KeyIdentifier | `KeyIdentifier`}. Implementations can use any string as the key
 *   identifier (e.g. JWK thumbprint, UUID generated by hosted KMS, etc.).
 * - Must support key generation, hashing, signing, and verifying operations.
 * - May be extended to support other cryptographic operations.
 * - Implementations of the `DsaApi` interface can be passed as an argument to the public API
 *   methods of Web5 libraries that involve key material (e.g., DID creation, VC signing, arbitrary
 *   data signing/verification, etc.).
 */
export interface DsaApi<
  GenerateKeyInput = KmsGenerateKeyParams,
  GenerateKeyOutput = KeyIdentifier,
  GetPublicKeyInput = KmsGetPublicKeyParams,
  DigestInput = KmsDigestParams,
  SignInput = KmsSignParams,
  VerifyInput = KmsVerifyParams
> extends AsymmetricKeyGenerator<GenerateKeyInput, GenerateKeyOutput, GetPublicKeyInput>,
          Hasher<DigestInput>,
          Signer<SignInput, VerifyInput> {
  /**
   *
   * @param params - The parameters for getting the key URI.
   * @param params.key - The key to get the URI for.
   * @returns The key URI.
   */
  getKeyUri(params: KmsGetKeyUriParams): Promise<KeyIdentifier>;
}

/**
 * The `CryptoApi` interface extends {@link DsaApi} with cipher, key conversion, key derivation,
 * and key wrapping capabilities, forming a comprehensive cryptographic API.
 *
 * This interface is designed for implementations that need the full suite of cryptographic
 * operations beyond just signing/hashing (e.g., encryption, key wrapping, key derivation).
 */
export interface CryptoApi<
  GenerateKeyInput = GenerateKeyParams,
  GenerateKeyOutput = Jwk,
  GetPublicKeyInput = GetPublicKeyParams,
  DigestInput = DigestParams,
  SignInput = SignParams,
  VerifyInput = VerifyParams,
  EncryptInput = CipherParams,
  DecryptInput = CipherParams,
  BytesToPublicKeyInput = BytesToPublicKeyParams,
  PublicKeyToBytesInput = PublicKeyToBytesParams,
  BytesToPrivateKeyInput = BytesToPrivateKeyParams,
  PrivateKeyToBytesInput = PrivateKeyToBytesParams,
  DeriveKeyInput = DeriveKeyParams,
  DeriveKeyOutput = Jwk,
  DeriveKeyBytesInput = DeriveKeyBytesParams,
  DeriveKeyBytesOutput = Uint8Array,
  WrapKeyInput = WrapKeyParams,
  UnwrapKeyInput = UnwrapKeyParams
> extends
  DsaApi<GenerateKeyInput, GenerateKeyOutput, GetPublicKeyInput, DigestInput, SignInput, VerifyInput>,
  Cipher<EncryptInput, DecryptInput>,
  AsymmetricKeyConverter<BytesToPublicKeyInput, PublicKeyToBytesInput, BytesToPrivateKeyInput, PrivateKeyToBytesInput>,
  KeyBytesDeriver<DeriveKeyBytesInput, DeriveKeyBytesOutput>,
  KeyWrapper<WrapKeyInput, UnwrapKeyInput> {

  /**
   * Derives a cryptographic key based on the provided input parameters.
   *
   * @param params - The parameters for the key derivation process.
   * @returns A Promise resolving to the derived key.
   */
  deriveKey(params: DeriveKeyInput): Promise<DeriveKeyOutput>;
}
