/**
 * Structured, machine-readable data attached to a `DwnError`.
 * Values are restricted to JSON primitives so the bag can be surfaced verbatim in a message reply `status.info`.
 */
export type DwnErrorInfo = Record<string, string | number | boolean>;

/**
 * A class that represents a DWN error.
 */
export class DwnError extends Error {
  /**
   * Structured, machine-readable data describing this error.
   * Surfaced verbatim as `status.info` when the error becomes a message reply,
   * so consumers can read error-specific values (e.g. the squash floor timestamp) without parsing prose.
   */
  public readonly info?: DwnErrorInfo;

  constructor (public code: string, message: string, options?: { info?: DwnErrorInfo }) {
    super(`${code}: ${message}`);

    this.name = 'DwnError';
    this.info = options?.info;
  }
}

/**
 * DWN SDK error codes.
 */
export enum DwnErrorCode {
  AuthenticateJwsMissing = 'AuthenticateJwsMissing',
  AuthenticateDescriptorCidMismatch = 'AuthenticateDescriptorCidMismatch',
  AuthenticationMoreThanOneSignatureNotSupported = 'AuthenticationMoreThanOneSignatureNotSupported',
  AuthorizationNotGrantedToAuthor = 'AuthorizationNotGrantedToAuthor',
  ComputeCidCodecNotSupported = 'ComputeCidCodecNotSupported',
  ComputeCidMultihashNotSupported = 'ComputeCidMultihashNotSupported',
  Ed25519InvalidJwk = 'Ed25519InvalidJwk',
  EncryptionControlReadUnauthorized = 'EncryptionControlReadUnauthorized',
  EncryptionControlValidateAudienceContextIdInvalid = 'EncryptionControlValidateAudienceContextIdInvalid',
  EncryptionControlValidateAudienceKeyIdMismatch = 'EncryptionControlValidateAudienceKeyIdMismatch',
  EncryptionControlValidateAudienceMissingRequiredTag = 'EncryptionControlValidateAudienceMissingRequiredTag',
  EncryptionControlValidateAudienceRolePathInvalid = 'EncryptionControlValidateAudienceRolePathInvalid',
  EncryptionControlValidateAudienceSealKeyIdMismatch = 'EncryptionControlValidateAudienceSealKeyIdMismatch',
  EncryptionControlValidateAudienceTagsMismatch = 'EncryptionControlValidateAudienceTagsMismatch',
  EncryptionControlValidateAudienceWriterUnauthorized = 'EncryptionControlValidateAudienceWriterUnauthorized',
  EncryptionControlValidateDeliveryAudienceMissing = 'EncryptionControlValidateDeliveryAudienceMissing',
  EncryptionControlValidateDeliveryMissingRequiredTag = 'EncryptionControlValidateDeliveryMissingRequiredTag',
  EncryptionControlValidateDeliveryRecipientAuthorityInvalid = 'EncryptionControlValidateDeliveryRecipientAuthorityInvalid',
  EncryptionControlValidateDeliveryRecipientMissing = 'EncryptionControlValidateDeliveryRecipientMissing',
  EncryptionControlValidateDeliveryRecipientRoleRecordMissing = 'EncryptionControlValidateDeliveryRecipientRoleRecordMissing',
  EncryptionControlValidateDeliveryTagsMismatch = 'EncryptionControlValidateDeliveryTagsMismatch',
  EncryptionControlValidateUnexpectedRecord = 'EncryptionControlValidateUnexpectedRecord',
  EncryptionProtocolValidateEncryptedDeliveryMissingEncryption = 'EncryptionProtocolValidateEncryptedDeliveryMissingEncryption',
  EncryptionProtocolValidateGrantKeyAuthorMismatch = 'EncryptionProtocolValidateGrantKeyAuthorMismatch',
  EncryptionProtocolValidateGrantKeyGrantScopeMismatch = 'EncryptionProtocolValidateGrantKeyGrantScopeMismatch',
  EncryptionProtocolValidateGrantKeyMissingRequiredTag = 'EncryptionProtocolValidateGrantKeyMissingRequiredTag',
  EncryptionProtocolValidateGrantKeyRecipientMismatch = 'EncryptionProtocolValidateGrantKeyRecipientMismatch',
  EncryptionProtocolValidateGrantKeyWrappedDeliveryInvalid = 'EncryptionProtocolValidateGrantKeyWrappedDeliveryInvalid',
  EncryptionProtocolValidateSchemaUnexpectedRecord = 'EncryptionProtocolValidateSchemaUnexpectedRecord',
  EventLogNotOpenError = 'EventLogNotOpenError',
  EventLogProgressGap = 'EventLogProgressGap',
  MessagesGrantAuthorizationMismatchedProtocol = 'MessagesGrantAuthorizationMismatchedProtocol',
  MessagesGrantAuthorizationSubscribeProtocolMismatch = 'MessagesGrantAuthorizationSubscribeProtocolMismatch',
  MessagesGrantAuthorizationUnfilteredSubscribeProtocolScope = 'MessagesGrantAuthorizationUnfilteredSubscribeProtocolScope',
  MessagesSubscribeAuthorizationFailed = 'MessagesSubscribeAuthorizationFailed',
  /**
   * Terminal subscription delivery error indicating the invoked grant no longer authorizes delivery.
   * Subscribers should not resubscribe with the same grant.
   */
  MessagesSubscribeDeliveryAuthorizationFailed = 'MessagesSubscribeDeliveryAuthorizationFailed',
  /**
   * Terminal subscription delivery error for non-authorization delivery failures.
   * Subscribers may resubscribe from their last cursor.
   */
  MessagesSubscribeDeliveryFailed = 'MessagesSubscribeDeliveryFailed',
  MessagesSubscribeEventLogUnimplemented = 'MessagesSubscribeEventLogUnimplemented',
  GeneralJwsVerifierGetPublicKeyNotFound = 'GeneralJwsVerifierGetPublicKeyNotFound',
  GeneralJwsVerifierInvalidSignature = 'GeneralJwsVerifierInvalidSignature',
  GeneralJwsVerifierMissingAlg = 'GeneralJwsVerifierMissingAlg',
  GeneralJwsVerifierMissingKid = 'GeneralJwsVerifierMissingKid',
  GrantAuthorizationGrantExpired = 'GrantAuthorizationGrantExpired',
  GrantAuthorizationGrantMissing = 'GrantAuthorizationGrantMissing',
  GrantAuthorizationGrantRevoked = 'GrantAuthorizationGrantRevoked',
  GrantAuthorizationInterfaceMismatch = 'GrantAuthorizationInterfaceMismatch',
  GrantAuthorizationMethodMismatch = 'GrantAuthorizationMethodMismatch',
  GrantAuthorizationNotGrantedForTenant = 'GrantAuthorizationNotGrantedForTenant',
  GrantAuthorizationNotGrantedToAuthor = 'GrantAuthorizationNotGrantedToAuthor',
  GrantAuthorizationGrantNotYetActive = 'GrantAuthorizationGrantNotYetActive',
  HdKeyDerivationPathInvalid = 'HdKeyDerivationPathInvalid',
  JwsVerifySignatureUnsupportedCrv = 'JwsVerifySignatureUnsupportedCrv',
  IndexInvalidCursorValueType = 'IndexInvalidCursorValueType',
  IndexInvalidCursorSortProperty = 'IndexInvalidCursorSortProperty',
  IndexInvalidSortPropertyInMemory = 'IndexInvalidSortPropertyInMemory',
  IndexMissingIndexableProperty = 'IndexMissingIndexableProperty',
  JwsDecodePlainObjectPayloadInvalid = 'JwsDecodePlainObjectPayloadInvalid',
  MessageStoreDeleteLogEntryMissing = 'MessageStoreDeleteLogEntryMissing',
  MessageStoreFingerprintScopeMutation = 'MessageStoreFingerprintScopeMutation',
  MessageStorePreSubstrateLayout = 'MessageStorePreSubstrateLayout',
  MessageStoreReplicationPositionOverflow = 'MessageStoreReplicationPositionOverflow',
  MessageStoreUpdateMessageAndIndexesCidMismatch = 'MessageStoreUpdateMessageAndIndexesCidMismatch',
  MessageStoreUpdateMessageAndIndexesMessageNotFound = 'MessageStoreUpdateMessageAndIndexesMessageNotFound',
  MessageStoreUpdateIndexesMessageNotFound = 'MessageStoreUpdateIndexesMessageNotFound',
  MessagePermissionGrantCreateInvocationAmbiguous = 'MessagePermissionGrantCreateInvocationAmbiguous',
  MessagePermissionGrantDescriptorPayloadMismatch = 'MessagePermissionGrantDescriptorPayloadMismatch',
  MessagePermissionGrantIdsDescriptorPayloadMismatch = 'MessagePermissionGrantIdsDescriptorPayloadMismatch',
  MessagePermissionGrantIdsEmpty = 'MessagePermissionGrantIdsEmpty',
  MessagePermissionGrantIdsNotCanonical = 'MessagePermissionGrantIdsNotCanonical',
  MessagePermissionGrantValidateInvocationAmbiguous = 'MessagePermissionGrantValidateInvocationAmbiguous',
  MessagesReadInvalidCid = 'MessagesReadInvalidCid',
  MessagesQueryAuthorizationFailed = 'MessagesQueryAuthorizationFailed',
  MessagesQueryReplicationFeedUnimplemented = 'MessagesQueryReplicationFeedUnimplemented',
  MessagesReadAuthorizationFailed = 'MessagesReadAuthorizationFailed',
  MessageGetInvalidCid = 'MessageGetInvalidCid',
  MessagesReadVerifyScopeFailed = 'MessagesReadVerifyScopeFailed',
  ParseCidCodecNotSupported = 'ParseCidCodecNotSupported',
  ParseCidMultihashNotSupported = 'ParseCidMultihashNotSupported',
  PermissionsProtocolCreateGrantScopeContextIdProtocolPathConflict = 'PermissionsProtocolCreateGrantScopeContextIdProtocolPathConflict',
  PermissionsProtocolCreateGrantRecordsScopeMissingProtocol = 'PermissionsProtocolCreateGrantRecordsScopeMissingProtocol',
  PermissionsProtocolCreateGrantSubtreeScopeMissingProtocol = 'PermissionsProtocolCreateGrantSubtreeScopeMissingProtocol',
  PermissionsProtocolCreateRequestScopeContextIdProtocolPathConflict = 'PermissionsProtocolCreateRequestScopeContextIdProtocolPathConflict',
  PermissionsProtocolCreateRequestRecordsScopeMissingProtocol = 'PermissionsProtocolCreateRequestRecordsScopeMissingProtocol',
  PermissionsProtocolCreateRequestSubtreeScopeMissingProtocol = 'PermissionsProtocolCreateRequestSubtreeScopeMissingProtocol',
  PermissionsProtocolGetScopeInvalidProtocol = 'PermissionsProtocolGetScopeInvalidProtocol',
  PermissionsProtocolValidateSchemaUnexpectedRecord = 'PermissionsProtocolValidateSchemaUnexpectedRecord',
  PermissionsProtocolValidateScopeContextIdProhibitedProperties = 'PermissionsProtocolValidateScopeContextIdProhibitedProperties',
  PermissionsProtocolValidateScopeSubtreeScopeMissingProtocol = 'PermissionsProtocolValidateScopeSubtreeScopeMissingProtocol',
  PermissionsProtocolValidateScopeProtocolMismatch = 'PermissionsProtocolValidateScopeProtocolMismatch',
  PermissionsProtocolValidateScopeMissingProtocolTag = 'PermissionsProtocolValidateScopeMissingProtocolTag',
  PermissionsProtocolValidateRevocationProtocolTagMismatch = 'PermissionsProtocolValidateRevocationProtocolTagMismatch',
  PermissionGrantParseMissingAuthorization = 'PermissionGrantParseMissingAuthorization',
  PermissionGrantParseMissingEncodedData = 'PermissionGrantParseMissingEncodedData',
  PermissionGrantParseMissingRecipient = 'PermissionGrantParseMissingRecipient',
  PermissionGrantParseMissingScope = 'PermissionGrantParseMissingScope',
  PermissionGrantParseMissingDateExpires = 'PermissionGrantParseMissingDateExpires',
  PermissionRequestParseMissingAuthorization = 'PermissionRequestParseMissingAuthorization',
  PermissionRequestParseMissingEncodedData = 'PermissionRequestParseMissingEncodedData',
  PermissionRequestParseMissingScope = 'PermissionRequestParseMissingScope',
  PrivateKeySignerUnableToDeduceAlgorithm = 'PrivateKeySignerUnableToDeduceAlgorithm',
  PrivateKeySignerUnableToDeduceKeyId = 'PrivateKeySignerUnableToDeduceKeyId',
  PrivateKeySignerUnsupportedCurve = 'PrivateKeySignerUnsupportedCurve',
  ProtocolAuthorizationActionNotAllowed = 'ProtocolAuthorizationActionNotAllowed',
  ProtocolAuthorizationActionRulesNotFound = 'ProtocolAuthorizationActionRulesNotFound',
  ProtocolAuthorizationCrossProtocolParentNotFound = 'ProtocolAuthorizationCrossProtocolParentNotFound',
  ProtocolAuthorizationIncorrectDataFormat = 'ProtocolAuthorizationIncorrectDataFormat',
  ProtocolAuthorizationIncorrectContextId = 'ProtocolAuthorizationIncorrectContextId',
  ProtocolAuthorizationIncorrectProtocolPath = 'ProtocolAuthorizationIncorrectProtocolPath',
  ProtocolAuthorizationInitialWriteRevalidationNotInitial = 'ProtocolAuthorizationInitialWriteRevalidationNotInitial',
  ProtocolAuthorizationDuplicateRoleRecipient = 'ProtocolAuthorizationDuplicateRoleRecipient',
  ProtocolAuthorizationEncryptionNotAllowed = 'ProtocolAuthorizationEncryptionNotAllowed',
  ProtocolAuthorizationEncryptionRequired = 'ProtocolAuthorizationEncryptionRequired',
  ProtocolAuthorizationEncryptionKeyAgreementMissing = 'ProtocolAuthorizationEncryptionKeyAgreementMissing',
  ProtocolAuthorizationEncryptionProtocolPathEntryMissing = 'ProtocolAuthorizationEncryptionProtocolPathEntryMissing',
  ProtocolAuthorizationEncryptionRoleAudienceEntryMissing = 'ProtocolAuthorizationEncryptionRoleAudienceEntryMissing',
  ProtocolAuthorizationEncryptionRoleAudienceMissing = 'ProtocolAuthorizationEncryptionRoleAudienceMissing',
  ProtocolAuthorizationImmutableRecord = 'ProtocolAuthorizationImmutableRecord',
  ProtocolAuthorizationInvalidSchema = 'ProtocolAuthorizationInvalidSchema',
  ProtocolAuthorizationInvalidType = 'ProtocolAuthorizationInvalidType',
  ProtocolAuthorizationMatchingRoleRecordNotFound = 'ProtocolAuthorizationMatchingRoleRecordNotFound',
  ProtocolAuthorizationMaxSizeInvalid = 'ProtocolAuthorizationMaxSizeInvalid',
  ProtocolAuthorizationMinSizeInvalid = 'ProtocolAuthorizationMinSizeInvalid',
  ProtocolAuthorizationRecordLimitStrategyNotImplemented = 'ProtocolAuthorizationRecordLimitStrategyNotImplemented',
  ProtocolAuthorizationSquashNotEnabled = 'ProtocolAuthorizationSquashNotEnabled',
  ProtocolAuthorizationSquashNotInitialWrite = 'ProtocolAuthorizationSquashNotInitialWrite',
  ProtocolAuthorizationSquashBackstop = 'ProtocolAuthorizationSquashBackstop',
  ProtocolAuthorizationStoredInitialWriteActionNotAllowed = 'ProtocolAuthorizationStoredInitialWriteActionNotAllowed',
  ProtocolAuthorizationStoredInitialWriteActionRulesNotFound = 'ProtocolAuthorizationStoredInitialWriteActionRulesNotFound',
  ProtocolAuthorizationStoredInitialWriteRoleMissingRecipient = 'ProtocolAuthorizationStoredInitialWriteRoleMissingRecipient',
  ProtocolAuthorizationMissingContextId = 'ProtocolAuthorizationMissingContextId',
  ProtocolAuthorizationMissingRuleSet = 'ProtocolAuthorizationMissingRuleSet',
  ProtocolAuthorizationParentRecordNotFound = 'ProtocolAuthorizationParentRecordNotFound',
  ProtocolAuthorizationParentlessIncorrectProtocolPath = 'ProtocolAuthorizationParentlessIncorrectProtocolPath',
  ProtocolAuthorizationNotARole = 'ProtocolAuthorizationNotARole',
  ProtocolAuthorizationParentNotFoundConstructingRecordChain = 'ProtocolAuthorizationParentNotFoundConstructingRecordChain',
  ProtocolAuthorizationProtocolNotFound = 'ProtocolAuthorizationProtocolNotFound',
  ProtocolAuthorizationRoleMissingRecipient = 'ProtocolAuthorizationRoleMissingRecipient',
  ProtocolAuthorizationTagsInvalidSchema = 'ProtocolAuthorizationTagsInvalidSchema',
  ProtocolsConfigureAuthorizationFailed = 'ProtocolsConfigureAuthorizationFailed',
  ProtocolsConfigureComposedProtocolNotInstalled = 'ProtocolsConfigureComposedProtocolNotInstalled',
  ProtocolsConfigureDuplicateActorInRuleSet = 'ProtocolsConfigureDuplicateActorInRuleSet',
  ProtocolsConfigureDuplicateRoleInRuleSet = 'ProtocolsConfigureDuplicateRoleInRuleSet',
  ProtocolsConfigureInvalidRefAlias = 'ProtocolsConfigureInvalidRefAlias',
  ProtocolsConfigureInvalidRefNodeHasDirectives = 'ProtocolsConfigureInvalidRefNodeHasDirectives',
  ProtocolsConfigureInvalidRefNotAtRoot = 'ProtocolsConfigureInvalidRefNotAtRoot',
  ProtocolsConfigureInvalidRefProtocolPath = 'ProtocolsConfigureInvalidRefProtocolPath',
  ProtocolsConfigureInvalidRefTargetThroughRef = 'ProtocolsConfigureInvalidRefTargetThroughRef',
  ProtocolsConfigureInvalidRecordLimit = 'ProtocolsConfigureInvalidRecordLimit',
  ProtocolsConfigureInvalidSize = 'ProtocolsConfigureInvalidSize',
  ProtocolsConfigureInvalidActionMissingOf = 'ProtocolsConfigureInvalidActionMissingOf',
  ProtocolsConfigureInvalidActionOfNotAnAncestor = 'ProtocolsConfigureInvalidActionOfNotAnAncestor',
  ProtocolsConfigureInvalidActionOfNotAllowed = 'ProtocolsConfigureInvalidActionOfNotAllowed',
  ProtocolsConfigureInvalidActionDeleteWithoutCreate = 'ProtocolsConfigureInvalidActionDeleteWithoutCreate',
  ProtocolsConfigureInvalidActionPruneWithoutCreate = 'ProtocolsConfigureInvalidActionPruneWithoutCreate',
  ProtocolsConfigureInvalidActionUpdateWithoutCreate = 'ProtocolsConfigureInvalidActionUpdateWithoutCreate',
  ProtocolsConfigureInvalidCrossProtocolOf = 'ProtocolsConfigureInvalidCrossProtocolOf',
  ProtocolsConfigureInvalidCrossProtocolRole = 'ProtocolsConfigureInvalidCrossProtocolRole',
  ProtocolsConfigureInvalidEncryptedAnyoneRead = 'ProtocolsConfigureInvalidEncryptedAnyoneRead',
  ProtocolsConfigureInvalidEncryptedCrossProtocolRole = 'ProtocolsConfigureInvalidEncryptedCrossProtocolRole',
  ProtocolsConfigureInvalidEncryptedRoleMissingKeyAgreement = 'ProtocolsConfigureInvalidEncryptedRoleMissingKeyAgreement',
  ProtocolsConfigureMissingEncryptedPathKeyAgreement = 'ProtocolsConfigureMissingEncryptedPathKeyAgreement',
  ProtocolsConfigureMissingTopLevelKeyAgreement = 'ProtocolsConfigureMissingTopLevelKeyAgreement',
  ProtocolsConfigureEncryptionPolicyImmutable = 'ProtocolsConfigureEncryptionPolicyImmutable',
  ProtocolsConfigureInvalidRecipientOfAction = 'ProtocolsConfigureInvalidRecipientOfAction',
  ProtocolsConfigureInvalidRuleSetRecordType = 'ProtocolsConfigureInvalidRuleSetRecordType',
  ProtocolsConfigureInvalidTagSchema = 'ProtocolsConfigureInvalidTagSchema',
  ProtocolsConfigureInvalidUsesAlias = 'ProtocolsConfigureInvalidUsesAlias',
  ProtocolsConfigureInvalidUsesProtocolUrl = 'ProtocolsConfigureInvalidUsesProtocolUrl',
  ProtocolsConfigureInvalidUsesSelfReference = 'ProtocolsConfigureInvalidUsesSelfReference',
  ProtocolsConfigureRecordNestingDepthExceeded = 'ProtocolsConfigureRecordNestingDepthExceeded',
  ProtocolsConfigureReservedEncryptionControlPath = 'ProtocolsConfigureReservedEncryptionControlPath',
  ProtocolsConfigureRoleDoesNotExistAtGivenPath = 'ProtocolsConfigureRoleDoesNotExistAtGivenPath',
  ProtocolsConfigureRoleParentContextDepthExceeded = 'ProtocolsConfigureRoleParentContextDepthExceeded',
  ProtocolsGrantAuthorizationQueryProtocolScopeMismatch = 'ProtocolsGrantAuthorizationQueryProtocolScopeMismatch',
  ProtocolsGrantAuthorizationScopeProtocolMismatch = 'ProtocolsGrantAuthorizationScopeProtocolMismatch',
  ProtocolsQueryUnauthorized = 'ProtocolsQueryUnauthorized',
  RecordsAuthorDelegatedGrantAndIdExistenceMismatch = 'RecordsAuthorDelegatedGrantAndIdExistenceMismatch',
  RecordsAuthorDelegatedGrantCidMismatch = 'RecordsAuthorDelegatedGrantCidMismatch',
  RecordsAuthorDelegatedGrantGrantedToAndOwnerSignatureMismatch = 'RecordsAuthorDelegatedGrantGrantedToAndOwnerSignatureMismatch',
  RecordsAuthorDelegatedGrantNotADelegatedGrant = 'RecordsAuthorDelegatedGrantNotADelegatedGrant',
  RecordsDecryptNoMatchingKeyEncryptedFound = 'RecordsDecryptNoMatchingKeyEncryptedFound',
  RecordsDecryptUnsupportedKeyDerivationScheme = 'RecordsDecryptUnsupportedKeyDerivationScheme',
  RecordsCountFilterMissingRequiredProperties = 'RecordsCountFilterMissingRequiredProperties',
  RecordsCountNestedProtocolPathContextIdInvalid = 'RecordsCountNestedProtocolPathContextIdInvalid',

  RecordsQueryCreateFilterPublishedSortInvalid = 'RecordsQueryCreateFilterPublishedSortInvalid',
  RecordsQueryParseFilterPublishedSortInvalid = 'RecordsQueryParseFilterPublishedSortInvalid',
  RecordsGrantAuthorizationConditionPublicationProhibited = 'RecordsGrantAuthorizationConditionPublicationProhibited',
  RecordsGrantAuthorizationConditionPublicationRequired = 'RecordsGrantAuthorizationConditionPublicationRequired',
  RecordsGrantAuthorizationDeleteProtocolScopeMismatch = 'RecordsGrantAuthorizationDeleteProtocolScopeMismatch',
  RecordsGrantAuthorizationQueryOrSubscribeProtocolScopeMismatch = 'RecordsGrantAuthorizationQueryOrSubscribeProtocolScopeMismatch',
  RecordsGrantAuthorizationScopeContextIdMismatch = 'RecordsGrantAuthorizationScopeContextIdMismatch',
  RecordsGrantAuthorizationScopeMismatch = 'RecordsGrantAuthorizationScopeMismatch',
  RecordsGrantAuthorizationScopeProtocolMismatch = 'RecordsGrantAuthorizationScopeProtocolMismatch',
  RecordsGrantAuthorizationScopeProtocolPathMismatch = 'RecordsGrantAuthorizationScopeProtocolPathMismatch',
  RecordsDerivePrivateKeyUnSupportedCurve = 'RecordsDerivePrivateKeyUnSupportedCurve',
  RecordsInvalidAncestorKeyDerivationSegment = 'RecordsInvalidAncestorKeyDerivationSegment',
  RecordsOwnerDelegatedGrantAndIdExistenceMismatch = 'RecordsOwnerDelegatedGrantAndIdExistenceMismatch',
  RecordsOwnerDelegatedGrantCidMismatch = 'RecordsOwnerDelegatedGrantCidMismatch',
  RecordsOwnerDelegatedGrantGrantedToAndOwnerSignatureMismatch = 'RecordsOwnerDelegatedGrantGrantedToAndOwnerSignatureMismatch',
  RecordsOwnerDelegatedGrantNotADelegatedGrant = 'RecordsOwnerDelegatedGrantNotADelegatedGrant',

  RecordsQueryFilterMissingRequiredProperties = 'RecordsQueryFilterMissingRequiredProperties',
  RecordsQueryNestedProtocolPathContextIdInvalid = 'RecordsQueryNestedProtocolPathContextIdInvalid',

  RecordsReadCreateFilterPublishedSortInvalid = 'RecordsReadCreateFilterPublishedSortInvalid',
  RecordsReadParseFilterPublishedSortInvalid = 'RecordsReadParseFilterPublishedSortInvalid',
  RecordsSubscribeEventLogUnimplemented = 'RecordsSubscribeEventLogUnimplemented',
  RecordsSubscribeFilterMissingRequiredProperties = 'RecordsSubscribeFilterMissingRequiredProperties',
  RecordsSubscribeNestedProtocolPathContextIdInvalid = 'RecordsSubscribeNestedProtocolPathContextIdInvalid',

  RecordsWriteAttestationIntegrityMoreThanOneSignature = 'RecordsWriteAttestationIntegrityMoreThanOneSignature',
  RecordsWriteAttestationIntegrityDescriptorCidMismatch = 'RecordsWriteAttestationIntegrityDescriptorCidMismatch',
  RecordsWriteAttestationIntegrityInvalidPayloadProperty = 'RecordsWriteAttestationIntegrityInvalidPayloadProperty',

  RecordsWriteCreateMissingSigner = 'RecordsWriteCreateMissingSigner',
  RecordsWriteCreateDataAndDataCidMutuallyExclusive = 'RecordsWriteCreateDataAndDataCidMutuallyExclusive',
  RecordsWriteCreateDataCidAndDataSizeMutuallyInclusive = 'RecordsWriteCreateDataCidAndDataSizeMutuallyInclusive',
  RecordsWriteCreateEncryptionAndEncryptionInputMutuallyExclusive = 'RecordsWriteCreateEncryptionAndEncryptionInputMutuallyExclusive',
  RecordsWriteCreateMissingProtocol = 'RecordsWriteCreateMissingProtocol',
  RecordsWriteDataCidMismatch = 'RecordsWriteDataCidMismatch',
  RecordsWriteDataSizeMismatch = 'RecordsWriteDataSizeMismatch',
  RecordsWriteGetEntryIdUndefinedAuthor = 'RecordsWriteGetEntryIdUndefinedAuthor',
  RecordsWriteGetNewestWriteRecordNotFound = 'RecordsWriteGetNewestWriteRecordNotFound',
  RecordsWriteGetInitialWriteNotFound = 'RecordsWriteGetInitialWriteNotFound',
  RecordsWriteImmutablePropertyChanged = 'RecordsWriteImmutablePropertyChanged',
  RecordsWriteMissingSigner = 'RecordsWriteMissingSigner',
  RecordsWriteMissingDataInPrevious = 'RecordsWriteMissingDataInPrevious',
  RecordsWriteMissingEncodedDataInPrevious = 'RecordsWriteMissingEncodedDataInPrevious',

  RecordsWriteNotAllowedAfterDelete = 'RecordsWriteNotAllowedAfterDelete',
  RecordsWriteOwnerAndTenantMismatch = 'RecordsWriteOwnerAndTenantMismatch',
  RecordsWriteSignAsOwnerDelegateUnknownAuthor = 'RecordsWriteSignAsOwnerDelegateUnknownAuthor',
  RecordsWriteSignAsOwnerUnknownAuthor = 'RecordsWriteSignAsOwnerUnknownAuthor',
  RecordsWriteValidateIntegrityAttestationMismatch = 'RecordsWriteValidateIntegrityAttestationMismatch',
  RecordsWriteValidateIntegrityContextIdMismatch = 'RecordsWriteValidateIntegrityContextIdMismatch',
  RecordsWriteValidateIntegrityContextIdNotInSignerSignaturePayload = 'RecordsWriteValidateIntegrityContextIdNotInSignerSignaturePayload',
  RecordsWriteValidateIntegrityDateCreatedMismatch = 'RecordsWriteValidateIntegrityDateCreatedMismatch',
  RecordsWriteValidateIntegrityEncryptionCidMissing = 'RecordsWriteValidateIntegrityEncryptionCidMissing',
  RecordsWriteValidateIntegrityEncryptionCidMismatch = 'RecordsWriteValidateIntegrityEncryptionCidMismatch',
  RecordsWriteValidateIntegrityEncryptionEphemeralPublicKeyInvalid = 'RecordsWriteValidateIntegrityEncryptionEphemeralPublicKeyInvalid',
  RecordsWriteValidateIntegrityEncryptionInitializationVectorInvalid = 'RecordsWriteValidateIntegrityEncryptionInitializationVectorInvalid',
  RecordsWriteValidateIntegrityRecordIdUnauthorized = 'RecordsWriteValidateIntegrityRecordIdUnauthorized',
  SchemaValidatorAdditionalPropertyNotAllowed = 'SchemaValidatorAdditionalPropertyNotAllowed',
  SchemaValidatorFailure = 'SchemaValidatorFailure',
  SchemaValidatorSchemaNotFound = 'SchemaValidatorSchemaNotFound',
  SchemaValidatorUnevaluatedPropertyNotAllowed = 'SchemaValidatorUnevaluatedPropertyNotAllowed',
  Secp256k1KeyNotValid = 'Secp256k1KeyNotValid',
  Secp256r1KeyNotValid = 'Secp256r1KeyNotValid',
  TimestampInvalid = 'TimestampInvalid',
  UrlProtocolNotNormalized = 'UrlProtocolNotNormalized',
  UrlProtocolNotNormalizable = 'UrlProtocolNotNormalizable',
  UrlSchemaNotNormalized = 'UrlSchemaNotNormalized',
  RecordsReadInitialWriteNotFound = 'RecordsReadInitialWriteNotFound',
};
