name: publish unstable

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  publish-npm-unstable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org/
      - run: bun install
      # builds all bundles
      - run: bun run build
      # Note - this is not required but it gives a clean failure prior to attempting a release if the GH workflow runner is not authenticated with npm.js
      - run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - run: bun run publish:unstable
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
