import type { PortableDid } from '@enbox/dids';
import type { ConnectClientMetadata, ConnectPermissionRequest, ConnectRequestType } from '@enbox/connect';
import type { ConnectHandler, ConnectResult, WalletConnectClientOptions } from '@enbox/auth';
import type { Readable, Writable } from 'node:stream';

import { WalletConnect } from '@enbox/auth';

import { openBrowser as defaultOpenBrowser, promptLine, renderTerminalQr } from './terminal.js';

export const DEFAULT_CLI_WALLET_URL = 'https://enbox-wallet.pages.dev';

/** Default requested session TTL for CLI connects. Wallets may clamp it. */
export const DEFAULT_CLI_SESSION_TTL_SECONDS = 30 * 24 * 60 * 60;

/** Well-known path on the wallet origin naming its preferred connect relay. */
export const WALLET_WELL_KNOWN_PATH = '/.well-known/enbox-connect';

const DEFAULT_WALLET_CONNECT_PATH = '/connect/app';
const WELL_KNOWN_FETCH_TIMEOUT_MS = 5_000;

export type PromptFunction = (question: string) => Promise<string>;
export type QrRenderer = (uri: string) => Promise<string> | string;
export type BrowserOpenFunction = (uri: string) => Promise<void> | void;

type WalletUrlState = {
  lastPromptedWalletUrl?: string;
};

export interface CliConnectHandlerOptions {
  /** Wallet app URL. A bare origin is normalized to `/connect/app`. */
  walletUrl?: string;

  /**
   * Connect relay URL. Usually the dwn-server URL already configured by the
   * hosting tool, with `/connect` available on that server.
   *
   * When omitted, the handler tries `connectServerUrlProvider`, then the
   * wallet origin's `/.well-known/enbox-connect` document, then prompts.
   */
  connectServerUrl?: string;

  /**
   * Optional late-bound relay URL provider for tool config stores.
   * `connectServerUrl` takes precedence when both are provided.
   */
  connectServerUrlProvider?: () => Promise<string | undefined> | string | undefined;

  /** Display name shown in the wallet approval screen. */
  appName?: string;

  /** Optional icon URL shown in the wallet approval screen. */
  appIcon?: string;

  /** Optional client/environment metadata for wallet session display. */
  clientMetadata?: ConnectClientMetadata;

  /**
   * Preferred session TTL in seconds. Defaults to 30 days
   * ({@link DEFAULT_CLI_SESSION_TTL_SECONDS}). Wallets may clamp this to
   * their policy maximum.
   */
  requestedSessionTtlSeconds?: number;

  /**
   * Request wallet grants to a local delegate DID generated by the relay client.
   * Defaults to true so CLI delegate signing keys stay in the requesting process.
   */
  preSupplyDelegateDid?: boolean;

  /** Open the generated wallet URL in the local default browser instead of printing a QR code. */
  openBrowser?: boolean;

  /** Called with the wallet authorization URL for embedding hosts. */
  onAuthUrl?: (uri: string) => Promise<void> | void;

  /** Prompt for the PIN shown by the wallet. */
  pinPrompt?: PromptFunction;

  /** Prompt for a wallet URL when `walletUrl` is omitted. */
  walletPrompt?: PromptFunction;

  /** Prompt for a connect relay URL when no option/provider value is available. */
  connectServerUrlPrompt?: PromptFunction;

  /** Milliseconds to wait for wallet approval. Defaults to 300 seconds. */
  timeoutMs?: number;

  /** Milliseconds between relay polling attempts. Defaults to 3000. */
  pollIntervalMs?: number;

  /** Terminal input stream used by default prompts. */
  input?: Readable;

  /** Terminal output stream used by default prompts and QR/link rendering. */
  output?: Writable;

  /** Custom QR renderer, primarily for host integration and tests. */
  qrRenderer?: QrRenderer;

  /** Custom browser opener, primarily for host integration and tests. */
  browserOpener?: BrowserOpenFunction;
}

/**
 * Create a CLI connect handler backed by the encrypted relay/PIN flow.
 *
 * Pass the handler to `createConnectionStore({ application, connectHandler })`, then call
 * the store's delegated `connect()` action.
 */
export function CliConnectHandler(options: CliConnectHandlerOptions = {}): ConnectHandler {
  const walletUrlState: WalletUrlState = {};

  return {
    async requestAccess(params: {
      permissionRequests: ConnectPermissionRequest[];
      delegatePortableDid?: PortableDid;
      requestType?: ConnectRequestType;
    }): Promise<ConnectResult | undefined> {
      if (params.requestType === 'refresh' && params.delegatePortableDid === undefined) {
        throw new Error('Connect: refresh requests require an existing `delegatePortableDid`.');
      }

      const walletUrl = await resolveWalletUrl(options, walletUrlState);
      const connectServerUrl = await resolveConnectServerUrl(options, walletUrl);
      const walletUri = buildWalletUri(walletUrl);
      const result = await WalletConnect.initClient({
        displayName                : options.appName ?? 'Enbox CLI',
        appIcon                    : options.appIcon,
        clientMetadata             : options.clientMetadata,
        requestedSessionTtlSeconds : options.requestedSessionTtlSeconds ?? DEFAULT_CLI_SESSION_TTL_SECONDS,
        preSupplyDelegateDid       : options.preSupplyDelegateDid ?? true,
        delegatePortableDid        : params.delegatePortableDid,
        requestType                : params.requestType,
        connectServerUrl,
        walletUri,
        permissionRequests         : params.permissionRequests,
        onWalletUriReady           : async (uri: string): Promise<void> => {
          await handleAuthUrl(uri, options);
        },
        validatePin    : async (): Promise<string> => resolvePin(options),
        timeoutMs      : options.timeoutMs,
        pollIntervalMs : options.pollIntervalMs,
      } satisfies WalletConnectClientOptions);

      // Grant validation (grantee + scope subset) runs in @enbox/auth's
      // shared connect path for every handler.
      return result;
    },
  };
}

async function resolveWalletUrl(options: CliConnectHandlerOptions, state: WalletUrlState): Promise<string> {
  if (options.walletUrl !== undefined && options.walletUrl.trim() !== '') {
    const normalized = normalizeUrl(options.walletUrl);
    if (normalized !== undefined) {
      return normalized;
    }

    throw new Error(`@enbox/cli: invalid wallet URL '${options.walletUrl}'. Enter a URL such as https://wallet.example.`);
  }

  const prompt = options.walletPrompt ?? defaultPrompt(options);
  while (true) {
    const defaultWalletUrl = state.lastPromptedWalletUrl ?? DEFAULT_CLI_WALLET_URL;
    const answer = (await prompt(`Wallet [${defaultWalletUrl}]: `)).trim();
    const walletUrl = answer === '' ? defaultWalletUrl : answer;
    const normalized = normalizeUrl(walletUrl);

    if (normalized !== undefined) {
      state.lastPromptedWalletUrl = normalized;
      return normalized;
    }

    writeLine(options, '@enbox/cli: invalid wallet URL. Enter a URL such as https://wallet.example.');
  }
}

async function resolveConnectServerUrl(options: CliConnectHandlerOptions, walletUrl: string): Promise<string> {
  if (options.connectServerUrl !== undefined && options.connectServerUrl.trim() !== '') {
    const normalized = normalizeUrl(options.connectServerUrl);
    if (normalized !== undefined) {
      return normalized;
    }

    throw new Error(`@enbox/cli: invalid connect relay URL '${options.connectServerUrl}'. Enter a URL such as https://dwn.example/connect.`);
  }

  const providedUrl = await options.connectServerUrlProvider?.();
  if (providedUrl !== undefined && providedUrl.trim() !== '') {
    const normalized = normalizeUrl(providedUrl);
    if (normalized !== undefined) {
      return normalized;
    }

    throw new Error(`@enbox/cli: invalid connect relay URL '${providedUrl}'. Enter a URL such as https://dwn.example/connect.`);
  }

  const discoveredUrl = await discoverWellKnownConnectServerUrl(options, walletUrl);
  if (discoveredUrl !== undefined) {
    return discoveredUrl;
  }

  const prompt = options.connectServerUrlPrompt ?? defaultPrompt(options);
  while (true) {
    const answer = (await prompt('Connect relay URL: ')).trim();
    if (answer === '') {
      throw new Error('@enbox/cli: connect relay URL is required.');
    }

    const normalized = normalizeUrl(answer);
    if (normalized !== undefined) {
      return normalized;
    }

    writeLine(options, '@enbox/cli: invalid connect relay URL. Enter a URL such as https://dwn.example/connect.');
  }
}

function defaultPrompt(options: CliConnectHandlerOptions): PromptFunction {
  return (question: string): Promise<string> => promptLine({
    input  : options.input,
    output : options.output,
    question,
  });
}

function buildWalletUri(walletUrl: string): string {
  const url = new URL(walletUrl);
  if (url.pathname === '' || url.pathname === '/') {
    url.pathname = DEFAULT_WALLET_CONNECT_PATH;
  }
  return url.toString();
}

/**
 * Discover the wallet's preferred connect relay from its well-known document.
 *
 * Fetches `{walletOrigin}/.well-known/enbox-connect` and returns the
 * `connectServerUrl` it names. Absent or unreachable documents resolve to
 * `undefined` so resolution falls through to the prompt; a document naming an
 * invalid URL is reported and ignored.
 */
async function discoverWellKnownConnectServerUrl(
  options: CliConnectHandlerOptions,
  walletUrl: string,
): Promise<string | undefined> {
  const wellKnownUrl = new URL(WALLET_WELL_KNOWN_PATH, new URL(walletUrl).origin).toString();

  let payload: unknown;
  try {
    const response = await fetch(wellKnownUrl, { signal: AbortSignal.timeout(WELL_KNOWN_FETCH_TIMEOUT_MS) });
    if (!response.ok) {
      return undefined;
    }
    payload = await response.json();
  } catch {
    return undefined;
  }

  const connectServerUrl = (payload as { connectServerUrl?: unknown } | null)?.connectServerUrl;
  if (typeof connectServerUrl !== 'string') {
    return undefined;
  }

  const normalized = normalizeUrl(connectServerUrl);
  if (normalized === undefined) {
    writeLine(options, `@enbox/cli: ignoring invalid connect relay URL in ${wellKnownUrl}.`);
    return undefined;
  }

  writeLine(options, `Using connect relay from wallet: ${normalized}`);
  return normalized;
}

function normalizeUrl(url: string): string | undefined {
  const trimmedUrl = url.trim();
  if (trimmedUrl === '') {
    return undefined;
  }

  const candidate = /^[a-zA-Z][a-zA-Z\d+.-]*:\/\//.test(trimmedUrl)
    ? trimmedUrl
    : `https://${trimmedUrl}`;

  try {
    const parsed = new URL(candidate);
    // Wallet and connect relay URLs are always fetched or opened over HTTP(S); any other
    // scheme would only fail later with a less understandable transport error.
    if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') {
      return undefined;
    }
    return parsed.toString();
  } catch {
    return undefined;
  }
}

async function resolvePin(options: CliConnectHandlerOptions): Promise<string> {
  const prompt = options.pinPrompt ?? defaultPrompt(options);
  const pin = (await prompt('Enter the PIN shown in your wallet: ')).trim();
  if (pin === '') {
    throw new Error('@enbox/cli: wallet PIN is required.');
  }
  return pin;
}

async function handleAuthUrl(uri: string, options: CliConnectHandlerOptions): Promise<void> {
  await options.onAuthUrl?.(uri);

  if (options.openBrowser === true) {
    writeLine(options, 'Opening wallet for approval...');
    await (options.browserOpener ?? defaultOpenBrowser)(uri);
    writeLine(options, 'Waiting for approval...');
    return;
  }

  writeLine(options, 'Scan with your wallet, or open the link in a browser:');
  writeLine(options, '');
  const qr = await (options.qrRenderer ?? renderTerminalQr)(uri);
  writeLine(options, qr);
  writeLine(options, '');
  writeLine(options, uri);
  writeLine(options, '');
  writeLine(options, 'Waiting for approval...');
}

function writeLine(options: CliConnectHandlerOptions, line: string): void {
  const output = options.output ?? process.stdout;
  output.write(`${line}\n`);
}
